### ISSUE TITLE
Add support for ShareX?

### ISSUE THREAD

**Issue by geekedtv** [Hubro/clipface#14]
Can you add support for ShareX to upload clips that are recorded using it? Any plans to add image upload support?

**Comment by wisewtf** [comment]
This, I can't stress this enough. ShareX integration would make this piece of software extremely invaluable.

**Comment by geekedtv** [comment]
> 
> 
> This, I can't stress this enough. ShareX integration would make this piece of software extremely invaluable.

Adding your reasons would add merit to your comment. Otherwise your comment itself is invaluable.

Seriously though, it's a request I'd like to see. Having to manually add my videos via ftp is a bit oldschool.

**Comment by Hubro** [comment]
ShareX looks pretty awesome, I'm surprised I haven't heard about it before.

If you are self-hosting Clipface, you should already be able to share ShareX clips by saving the clips to the Clipface clip folder. If you are running Clipface on a remote host, you could upload clips by mounting the remote clip directory to a local directory using something like [SSHFS-Win](https://github.com/billziss-gh/sshfs-win), then use that as the target directory for ShareX.

Otherwise, Clipface would first need clip upload support over HTTP, which it doesn't yet. It's on the roadmap though.

> Any plans to add image upload support?

No plans for image support. Clipface is intended to be an open source, self hosted equivalent of a service like Streamable, i.e. video sharing. I could change my mind, though.

**Comment by Hubro** [comment]
> Seriously though, it's a request I'd like to see. Having to manually add my videos via ftp is a bit oldschool.

Have you tried the FTP file uploader in ShareX? Or is that what you mean by "manually add my videos via FTP"? :smile:

**Comment by Snnackss** [comment]
#you could upload clips by mounting the remote clip directory to a local directory using something like SSHFS-Win, then use that as the target directory for ShareX.

This is exactly the type of thing I needed. This is awesome. Thanks for sharing this.

**Comment by wisewtf** [comment]
> 
> 
> > This, I can't stress this enough. ShareX integration would make this piece of software extremely invaluable.
> 
> Adding your reasons would add merit to your comment. Otherwise your comment itself is invaluable.
> 
> Seriously though, it's a request I'd like to see. Having to manually add my videos via ftp is a bit oldschool.

What? This comment makes 0 sense. ShareX intergration is pretty self-explanatory. And as it happened Hubro saw the potential once they discovered the software.

Also

> Otherwise your comment itself is invaluable.

Why, thank you :^)


> Otherwise, Clipface would first need clip upload support over HTTP, which it doesn't yet. It's on the roadmap though.

Thank you for this, I was unaware because I haven't taken the time to read the documentation yet. Also thank you for taking the time to read out suggestions.
