### ISSUE TITLE
Add pagination of clip list

### ISSUE THREAD

**Issue by Hubro** [Hubro/clipface#7]
The rendering performance of the clip list is suffering as the number of clips increases. Add pagination of the clip list to keep navigation snappy. It's important that if a user is navigating clips on page other than the first page, watches a clip and then presses "back", they should be taken to the same page they were on, and preferably also the same scroll position.

The number of clips per page should be configurable from the front-end, but the default number should also be configurable from the config file with the key `clips_per_page`.

**Comment by Hubro** [comment]
This is now implemented and the official Docker image has been updated.

![image](https://user-images.githubusercontent.com/597206/130320023-e131386a-cef8-4993-9952-5b2884ada1eb.png)

![image](https://user-images.githubusercontent.com/597206/130320024-b896d891-c27f-4eee-9d6b-cb1ae056a031.png)

**Comment by Hubro** [comment]
@Snnackss Want do give this a test? :slightly_smiling_face:

**Comment by Snnackss** [comment]
I like this because I'm not even 100 clips in and I was noticing some slow down. I can always change the max number of clips on a page, but this does dwindle search results down to the clips on the page you're currently looking at. Usually when I upload a clip, I search for the clip and then copy the link. So, this doesn't mean that this new feature is broken, but I think it brings up a new idea of having a 'Sort By' option of some sorts. I do see you number all of your clips so it's in order, but would it be possible to do this and have an option to sort by the "Saved" category so that way new clips can be at the top? This way it's possible to take advantage of the performance boost the pages gives, but it also prevents having to dig around to find the clip you just uploaded without adding the number in front of the clip name in the file name.

**Comment by Hubro** [comment]
> but this does dwindle search results down to the clips on the page you're currently looking at

I'm not sure I understand what you meant here, could you clarify?

> ... but I think it brings up a new idea of having a 'Sort By' option of some sorts. I do see you number all of your clips so it's in order, but would it be possible to do this and have an option to sort by the "Saved" category so that way new clips can be at the top?

Wow, honestly I thought it already sorted by saved time by default :S I've been in the habit of numbering my clips for so long.

Table sorting is a pretty important feature anyway, I'll make that my next task. "Saved" will be the default column.

**Comment by Snnackss** [comment]
> I'm not sure I understand what you meant here, could you clarify?

Okay, I take what I said back. Yesterday I guess I misspelled what I was looking for and assumed it did not show up in search results because it was on a separate page from the one I was on. I just double checked and it works fine.


> Table sorting is a pretty important feature anyway, I'll make that my next task. "Saved" will be the default column.

Awesome.
