### ISSUE TITLE
"An unexpected error has occurred." on Ubuntu 20.04

### ISSUE THREAD

**Issue by Snnackss** [Hubro/clipface#9]
I have a feeling this is related to the path to the folder containing the clips, but when I start the container in docker and go to the web server, it is blank and there is a small text that says "An unexpected error has occurred." I have tried several ports and tried different ways of typing the file path and have had no luck. Currently I am replacing "-v /host/path/to/clips:/clips \" with "-v /mnt/PLEXTHREE/Clips:/clips \".

Is that what I am doing wrong? Other than that the only thing I could think of is I am missing some dependencies.

**Comment by Hubro** [comment]
If you check the Docker logs:

    docker logs my-clipface-container

You will probably find that it crashes because it can't find a config file.

I intended the config file to be optional, but I clearly didn't test that well enough :smile: Sorry about that.

I have pushed an update to Docker Hub now that should resolve that issue. Please try again.
